### ISSUE TITLE
렌더링 관련 이슈

### ISSUE THREAD

**Issue by eunjios** [NewRecsys/howcanai-frontend#1]
## Description
- `/chat` 에서 `/chat/:id` 이동 시, `:id` 에 해당하는 `chatDetail` 데이터 잘 받아옴
- `<router-link>`로 `/chat/:id` 간 이동 시, URL 은 잘 바뀌는데 바뀐`chatDetail` 로 리렌더링 안 됨
- 중첩 라우터라서 그런 것 같음 렌더링 되기 전에 그래서 chatList 가 빈 배열로 나옴 

## Trials
1. `<router-view :key="$route.fullPath">`
2. chatDetail fetch 전에 reset
3. docs에서 권장하는 방식 watch
```javascript
watch: {
    '$route' (to, from) {
      // 경로 변경에 반응하여...
}
```

## TODO
**렌더링 관련**
- [x] Stack Overflow 확인
- [x] `route/index.js` 파일 훅 확인
- [x] 라우터가 아닌 컴포넌트 단위로 watch 사용해보기
- [x] 결과적으로 `/chat/:id` 간 이동 시 렌더링 잘 되게 고치기
